name:                nonempty-containers
version:             0.3.4.2
github:              "mstksg/nonempty-containers"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"
tested-with:         GHC >= 8.4

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Non-empty variants of containers data types, with full API
category:            Data Structures

description: |
  Efficient and optimized non-empty versions of types from /containers/.
  Inspired by /non-empty-containers/ library, except attempting a more
  faithful port (with under-the-hood optimizations) of the full /containers/
  API. Also contains a convenient typeclass abstraction for converting
  betwewen non-empty and possibly-empty variants. See README.md for more
  information.

ghc-options:
- -Wall
- -Wcompat
# - -Werror=incomplete-patterns
- -Wredundant-constraints

dependencies:
- base >= 4.9 && < 5
- comonad
- containers >= 0.5.9
- nonempty-vector
- semigroupoids
- these
- vector

library:
  source-dirs: src
  dependencies:
  - deepseq
  - aeson

tests:
  nonempty-containers-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hedgehog >= 1.0
    - hedgehog-fn >= 1.0
    - nonempty-containers
    - tasty
    - tasty-hedgehog >= 1.0
    - text
